USE emmetblue;

CREATE TABLE student_class_rel (
	rel_id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	student_id TINYINT UNSIGNED NOT NULL UNIQUE,
	class_id TINYINT UNSIGNED NOT NULL,
	last_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

	FOREIGN KEY (student_id) REFERENCES student_profile_info(profile_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (class_id) REFERENCES class_info(class_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE student_class_history (
	reason_id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	student_id TINYINT UNSIGNED NOT NULL,
	prev_class TINYINT UNSIGNED NOT NULL,
	next_class TINYINT UNSIGNED NOT NULL,
	modify_reason VARCHAR(100),
	modify_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (student_id) REFERENCES student_profile_info(profile_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (prev_class) REFERENCES class_info(class_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (next_class) REFERENCES class_info(class_id) ON UPDATE CASCADE ON DELETE CASCADE
)

